---
- name: New users created
  hosts: all
  become: true
  vars:
    web_users:
      - admin
      - member
      - developer
  tasks:
    - name: Create database users
      user: 
        name: "{{item}}"
        state: present
      loop: "{{ db_users}}"
      when: "'databases' in group_names"
      notify: Reboot system 

    - name: Create web servers
      user: 
        name: "{{item}}"
        state: present
      loop: "{{web_users}}"
      when: "'webservers' in group_names"
      notify: Reboot system
  handlers:
    - name: Reboot system
      reboot: