---
- name: Utilize Block rescue and always
  hosts: databases 
  become: true
  
  tasks:
    - name: Update database
 
      block:
        - name: Display and update message
          debug: 
            msg: "Updating databases"
        
        - name: Update postgresSQL server to latest version
          yum:
            name: postgresql-server
            state: latest
      
      rescue:
        - name: Display error messages that databases will be restarted
          debug:
            msg: "Update failed. Restarting databases to correct issues"

        - name: Restart the databases if upgrade failed
          service:
            name: postregsql
            state: restarted 
      
      always:
        - name: Notify user of reboot after update attempt
          debug:
            msg: "Update has been completed. See previus output for status. Rebooting system now"
        
        - name: Rebot the system
          reboot:

      
